args <- commandArgs(trailingOnly=TRUE)
.libPaths(c(args[1],.libPaths()))
library(LinkEDA)
ls_register_dataset("corr-smoke",data.frame(x=c(1,2,3,4,5),y=c(2,5,4,9,10)))
ns <- asNamespace("LinkEDA");original <- get(".rls_send",ns)
unlockBinding(".rls_send",ns)
assign(".rls_send",function(parts,...) {writeLines(as.character(parts),args[2]);"OK"},ns)
lockBinding(".rls_send",ns)
LinkEDA:::.rls_handle_correlation_needed(c("CORRELATION_NEEDED","corr-smoke-matrix","corr-smoke","1","1","all","pearson","pairwise","2","x","y","0"))
