pkgload::load_all('.',quiet=TRUE,compile=FALSE,export_all=FALSE)
set.seed(42)
d <- data.frame(age=rnorm(60,40,5),score=rnorm(60),group=factor(rep(c('Control','Treatment'),30)))
d$age[c(1:8,21:24)] <- NA; d$score[13:24] <- NA
ls_register_dataset('missing_native',d)
x <- ls_missing_data_overview('missing_native',c('age','score'),native=FALSE)
x <- LinkEDA:::.rls_missing_pattern_action(x$summary$id,'little',native=FALSE)
x <- LinkEDA:::.rls_missing_pattern_action(x$summary$id,'descriptives','all',native=FALSE)
source <- LinkEDA:::.rls_dataset_record('missing_native')
writeLines(c('REGISTER_DATASET_SILENT',source$group,LinkEDA:::.rls_variable_payload(source$data,source$variable_metadata),LinkEDA:::.rls_dataframe_payload(source$data,source$variable_metadata,dataset_record=source)),'/tmp/missing-source.txt')
dataset <- LinkEDA:::.rls_dataset_record(x$summary$group)
writeLines(c('REGISTER_DATASET_SILENT',dataset$group,LinkEDA:::.rls_variable_payload(dataset$data,dataset$variable_metadata),LinkEDA:::.rls_dataframe_payload(dataset$data,dataset$variable_metadata,dataset_record=dataset)),'/tmp/missing-register.txt')
writeLines(LinkEDA:::.rls_table1_native_payload(LinkEDA:::.rls_table1_record(x$descriptive)),'/tmp/missing-descriptives.txt')
writeLines(LinkEDA:::.rls_table1_native_payload(x$summary),'/tmp/missing-summary.txt')
writeLines(LinkEDA:::.rls_table1_native_payload(x$little_table),'/tmp/missing-little.txt')
writeLines(c(x$summary$id,x$descriptive$id,x$little_table$id),'/tmp/missing-report-ids.txt')
